### ISSUE TITLE
遭遇查询余额错误，这个怎么整？

### ISSUE THREAD

**Issue by zouwei** [okeyzero/jupStaker_SOL#1]
![image](https://github.com/okeyzero/jupStaker_SOL/assets/16266571/65519dc5-3021-45cd-b848-cd1f3cf82a98)

**Comment by zouwei** [comment]
![image](https://github.com/okeyzero/jupStaker_SOL/assets/16266571/20f32054-d14e-4654-885b-7925c7f7f75f)
我将依赖包升级到最新，结果初始化就遭遇报错了。请求作者大神帮助

**Comment by okeyzero** [comment]
你如果不会调试的话 就先别更新  因为我不清楚你具体得代码

**Comment by zouwei** [comment]
感谢大佬，我已经测试通过了
![image](https://github.com/okeyzero/jupStaker_SOL/assets/16266571/5c1dc8dc-5c07-4563-ae33-e92aa99c2b7d)

**Comment by zouwei** [comment]
大佬能否实现批量转账sol和jup的功能？然后就是归集，或许还有其他开源项目实现，我觉得可以找一找，炒一炒，聚合起来，打造最牛工具。
