### ISSUE TITLE
Does the voting code actual?

### ISSUE THREAD

**Issue by kartashovio** [okeyzero/jupStaker_SOL#2]
Thank you for such a great solution. I see that the code was written a week ago. Please tell me, did the voting code work in the last votes? Unfortunately, all voting is closed now and there is no way to check.

**Comment by okeyzero** [comment]
Yes, so far, the code has been valid, but you need to modify the voting data according to the readme document.

**Comment by kartashovio** [comment]
Thanks for the comprehensive answer!
