### ISSUE TITLE
How to claim lfg.jup.ag? 

### ISSUE THREAD

**Issue by kartashovio** [okeyzero/jupStaker_SOL#6]
I understand that this is not in this script and I want to ask the community if there is a script for the jup launchpads somewhere? This worries me because I do not know how to collect rewards from wallets in the future.

**Comment by okeyzero** [comment]
I'll add it when I have time.

**Comment by okeyzero** [comment]
> u can talk to me privately.

Yeah, but I don't have open source. You can talk to me privately.

**Comment by kartashovio** [comment]
@okeyzero check twitter pm please
