### ISSUE TITLE
Stake() not working anymore

### ISSUE THREAD

**Issue by kartashovio** [okeyzero/jupStaker_SOL#7]
Until a few days ago, everything was working fine. I also considered the possibility that I made too many edits to the code. I downloaded the original version of the repository again, and the code does not work anyway.

`Error: AnchorError thrown in programs/locked-voter/src/instructions/increase_locked_amount.rs:84Error Code: LockupDurationTooShort. Error Number: 6000. Error Message: Lockup duration must at least be the min stake duration.`

[Tx example](https://solscan.io/tx/4imkqzfXLxaAKwgbpQPtZwNJCwGy45BKVF2F1rZU8D1kYvwEYTVwH845QhozdaNMUgKN2R1jjkHwuwPaEoQ7cfww)

![Screenshot_4](https://github.com/okeyzero/jupStaker_SOL/assets/60577846/b7a2cd81-ae31-4309-a233-a068c8f1716d)

**Comment by okeyzero** [comment]
> Program log: AnchorError thrown in programs/locked-voter/src/instructions/increase_locked_amount.rs:84. Error Code: LockupDurationTooShort. Error Number: 6000. Error Message: Lockup duration must at least be the min stake duration.

**Comment by kartashovio** [comment]
@okeyzero could you say please, is this only my problem? i dont have experience in this, and i don't know how to solve this problem. at least i couple advices

**Comment by okeyzero** [comment]
![image](https://github.com/okeyzero/jupStaker_SOL/assets/48344256/e90573db-e8c9-4dc0-8795-72601ba72d4a)
I've tested it and it doesn't seem to be a problem, so you can contact me on Twitter and I'll test it further.

**Comment by kartashovio** [comment]
> ![image](https://private-user-images.githubusercontent.com/48344256/327959507-e90573db-e8c9-4dc0-8795-72601ba72d4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDM4MzMsIm5iZiI6MTcxNDkwMzUzMywicGF0aCI6Ii80ODM0NDI1Ni8zMjc5NTk1MDctZTkwNTczZGItZThjOS00ZGMwLTg3OTUtNzI2MDFiYTcyZDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEwMDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NmVkNWMxZjBlY2U0YmY1MDliMDE1NjBlYTI0OTIxN2Q3MDY0ODgwNzY3MmVkNTYzYWVlYmI2MDQ4M2ViNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UCk0BIpK-Og3XwGiScppGGA06bbLyppjOlAozw2I99U) I've tested it and it doesn't seem to be a problem, so you can contact me on Twitter and I'll test it further.

@okeyzero are you sure, that this is screenshot for TYPE=1? name your twitter please

**Comment by kartashovio** [comment]
@okeyzero can you name please your twitter?

**Comment by okeyzero** [comment]
> 大佬你的推特是哪个呀
0xNaiXi

**Comment by okeyzero** [comment]
> @okeyzero can you name please your twitter? upd: I have written to you in private messages

0xNaiXi

**Comment by okeyzero** [comment]
注意到了这个问题 ，这个问题 是由于 toggleMaxLock  和 increaseLockedAmount 执行命令顺序上错误引起的。
解决方法：
需要修改两个地方：
1. 第 240 行  `let signature = await this.toggleMaxDuration(!0, [...g, instruction]);` 修改成 
`let signature = await this.toggleMaxDuration(!0, [...g], [instruction]);`

2, 第358 行 ，整个 toggleMaxDuration 函数修改成
```
  async toggleMaxDuration(e, t, r) {
    let [a] = await this.getOrCreateEscrow();
    t.unshift(
      ComputeBudgetProgram.setComputeUnitPrice({
        microLamports: UNIT_PRICE,
      }),
      ComputeBudgetProgram.setComputeUnitLimit({ units: 800000 })
    );

    return this.program.methods
      .toggleMaxLock(e)
      .accounts({
        escrow: a,
        locker: locker,
        escrowOwner: this.wallet.publicKey,
      })
      .preInstructions(t || [])
      .postInstructions(r || [])
      .rpc();
  }
```

这样就可以更改为正确的 指令执行顺序。有什么问题 可以继续联系我

**Comment by kartashovio** [comment]
@okeyzero Now everything is fine! I have checked these changes, there are no more problems. I checked 1 wallet and it was successful. Thank you.
